#!/bin/bash

# ===================================================================================================
# Init
# ===================================================================================================

boxer_initbox() {
    if [[ $# < 1 ]]; then
        echo "Please provide box-name: initbox <boxname>"
        return 
    fi

    echo "Initializing Box $1"
    cd ~/machines
    mkdir -p $1
    cd $1
    touch .box
    export CURRENTBOX=$1

    boxer_log "Initialized box $1"
}

boxer_loadbox() {
    cd ~/machines/$1
    export CURRENTBOX=$1
    source ~/machines/$1/targets.txt
}

# ===================================================================================================
# Add
# ===================================================================================================

boxer_log() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    local str="[[$(date)]]: $@" 
    echo $str >> ~/machines/$CURRENTBOX/log.txt
    echo $str
}

boxer_addtarget() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi


    if [[ $# -ge 1 ]]; then
    	if [[ ! -f ~/machines/$CURRENTBOX/targets.txt ]]; then
		local targetname=TARGET
		echo "export $targetname=$1" >> ~/machines/$CURRENTBOX/targets.txt
	else
		local targetname=TARGET$(wc -l ~/machines/$CURRENTBOX/targets.txt | awk '{print $1}')
        	echo "export $targetname=$1" >> ~/machines/$CURRENTBOX/targets.txt
	fi
    fi

    if [[ $# -ge 2 ]]; then
        echo "$1    $2" | sudo tee -a /etc/hosts
    fi

    source ~/machines/$CURRENTBOX/targets.txt
    boxer_log "Added target: $targetname" 
}


boxer_addcreds() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    echo $1 >> ~/machines/$CURRENTBOX/creds.txt 
    boxer_log "Added creds: $1" 
}

boxer_addhash() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    echo $1 >> ~/machines/$1/hashes.txt 
    boxer_log "Added hash: $1" 
}

boxer_addnote() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    boxer_log "Updated notes." 

    if [[ $# < 1 ]]; then
        vim ~/machines/$CURRENTBOX/notes.txt
        return
    fi

    echo $@ >> ~/machines/$CURRENTBOX/notes.txt 
}

boxer_screenshot() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    local dir=~/machines/$CURRENTBOX/screenshots

    if [[ ! -d $dir ]]; then
        mkdir $dir
    fi

    local nscreens=$(($(ls -al $dir | wc -l ) - 3))
    local screenpath=$dir/screenshot_$nscreens.png

    xfce4-screenshooter
    xclip -selection c -o -t image/png > $screenpath
    echo "$screenpath" | xclip -selection c

    boxer_log "Saved at $dir/screenshot_$nscreens.png. (Path stored in clipboard)"
}

boxer_addloot() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    if [[ -f $1 ]]; then
	    local latestfile=$(readlink -f $1)
    else
        if [[ -d $1 ]]; then
	    local downloadsdir=$(readlink -f $1)
        else
    	    local downloadsdir=~/Downloads
        fi
	local file=$(ls -alt $downloadsdir --ignore=. --ignore=.. | head -n 2 | tail -n 1 | awk '{print $9}')
        local latestfile=$downloadsdir/$file
    fi

    local dir=~/machines/$CURRENTBOX/loot

    if [[ ! -d $dir ]]; then
	mkdir $dir
    fi

    mv $latestfile $dir

    boxer_log "Added $latestfile to loot."
}


# ===================================================================================================
# Show 
# ===================================================================================================

boxer_showlog() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    cat ~/machines/$CURRENTBOX/log.txt 
}

boxer_shownotes() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    cat ~/machines/$CURRENTBOX/notes.txt 
}

boxer_showcreds() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    cat ~/machines/$CURRENTBOX/creds.txt 
}

boxer_showhashes() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    cat ~/machines/$CURRENTBOX/hashes.txt 
}

boxer_showtargets() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    echo "Targets   ========================"
    echo ""
    cat ~/machines/$CURRENTBOX/targets.txt
    echo ""
    echo "Host File ========================"
    cat /etc/hosts
}

# Define the completion function
_boxer_loadbox() {
    local boxes=("${(@f)$(find . -name .box | sed -e 's/^\.\/\(.*\)\/\.box/\1/g')}")

    compadd -a boxes
}

compdef _boxer_loadbox boxer_loadbox


boxer_run() {
    if [[ ! $CURRENTBOX ]]; then
        echo "Please run initbox or loadbox first!"
        return
    fi

    a=$@

    local outpath=~/machines/$CURRENTBOX/${${a// /_}//\//}.txt
    boxer_log "Running $a (See $outpath)"

    $@ | tee $outpath
}

compdef _command boxer_run

